name: Take snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '35 15 * * *'

jobs:
  build:
    runs-on: macOS-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: ajilraju/action-date@v0.0.1
    - name: Update README
      run: |-
        Rscript -e "install.packages('devtools')"
        Rscript -e "devtools::install_github(\"mcguinlu/medrxivr\")"
        Rscript -e "install.packages('dplyr')"
        Rscript -e "source(\"snapshot_GHA.R\")"
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Daily snapshot: `date +'%Y-%m-%d %H:%M'`" -a || echo "No changes to commit"
        git push